In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

In [2]:
# Read Files
sector = pd.read_csv("sector_tickers.csv")
friday = pd.read_csv("fridaytest.csv", header=None)
stock = pd.read_csv("stock_holidays.csv")

In [3]:
sector.head()

,Unnamed: 0,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,0,1/3/2000,26.671881,26.687500,25.937500,25.968750,16.565908,140500,XLB
1,1,1/4/2000,26.000000,26.046881,25.609381,25.718750,16.406433,258000,XLB
2,2,1/5/2000,26.015619,26.812500,25.750000,26.781250,17.084217,102700,XLB
3,3,1/6/2000,26.796881,27.734381,26.781250,27.468750,17.522791,1335000,XLB
4,4,1/7/2000,27.750000,27.937500,27.453119,27.453119,17.512810,620100,XLB

In [4]:
friday.head()

            0
0  2001-01-05
1  2001-01-12
2  2001-01-19
3  2001-01-26
4  2001-02-02

In [5]:
friday.columns=["Date"]

In [6]:
type(friday["Date"][0])

str

In [7]:
stock.head()

   Unnamed: 0        Date                              Holiday
0         0.0  12/31/2010                       New Year's Day
1         1.0   1/17/2011  Birthday of Martin Luther King, Jr.
2         2.0   2/21/2011                      President's Day
3         3.0   4/22/2011                          Good Friday
4         4.0   5/30/2011                         Memorial Day

In [8]:
sector=sector[["Date", "Open", "High", "Low", "Close", "Adj Close", "Volume", "Ticker"]]

In [9]:
sector.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker
0,1/3/2000,26.671881,26.687500,25.937500,25.968750,16.565908,140500,XLB
1,1/4/2000,26.000000,26.046881,25.609381,25.718750,16.406433,258000,XLB
2,1/5/2000,26.015619,26.812500,25.750000,26.781250,17.084217,102700,XLB
3,1/6/2000,26.796881,27.734381,26.781250,27.468750,17.522791,1335000,XLB
4,1/7/2000,27.750000,27.937500,27.453119,27.453119,17.512810,620100,XLB

In [10]:
stock=stock[['Date', 'Holiday']]

In [11]:
stock.head()

         Date                              Holiday
0  12/31/2010                       New Year's Day
1   1/17/2011  Birthday of Martin Luther King, Jr.
2   2/21/2011                      President's Day
3   4/22/2011                          Good Friday
4   5/30/2011                         Memorial Day

In [12]:
merge_table = pd.merge(stock, sector, on="Date")
merge_table.head(50)

,Date,Holiday,Open,High,Low,Close,Adj Close,Volume,Ticker
0,12/31/2010,New Year's Day,38.389999,38.540001,38.310001,38.410000,32.195354,2424700,XLB
1,12/31/2010,New Year's Day,68.129997,68.500000,67.930000,68.250000,55.488960,4444500,XLE
2,12/31/2010,New Year's Day,12.908205,12.973192,12.891957,12.956945,8.443467,27080300,XLF
3,12/31/2010,New Year's Day,25.209999,25.240000,25.090000,25.190001,21.842997,6352100,XLK
4,12/31/2010,New Year's Day,31.330000,31.459999,31.290001,31.340000,23.045191,2171300,XLU
5,12/31/2010,New Year's Day,31.540001,31.570000,31.430000,31.500000,27.345753,3908500,XLV
6,12/31/2010,New Year's Day,37.470001,37.480000,37.290001,37.410000,33.062931,2212600,XLY
7,4/29/2013,Good Friday,39.009998,39.529999,38.880001,39.490002,34.744102,6944200,XLB
8,4/29/2013,Good Friday,77.650002,78.279999,77.300003,77.959999,65.830391,12214700,XLE
9,4/29/2013,Good Friday,15.150285,15.174655,15.085297,15.150285,10.257263,36910900,XLF
10,4/29/2013,Good Friday,30.110001,30.549999,30.110001,30.469999,27.405146,8256000,XLK
11,4/29/2013,Good Friday,41.130001,41.380001,40.930000,41.320000,33.249065,5835800,XLU
12,4/29/2013,Good Friday,47.580002,47.860001,47.580002,47.689999,43.326698,3950000,XLV
13,4/29/2013,Good Friday,54.509998,54.669998,54.279999,54.459999,49.873486,3157800,XLY
14,4/25/2016,Good Friday,47.160000,47.160000,46.689999,47.049999,44.099194,4601900,XLB
15,4/25/2016,Good Friday,66.809998,66.820000,65.790001,66.290001,60.142891,17234300,XLE
16,4/25/2016,Good Friday,19.049553,19.106417,18.952072,19.090170,13.803587,38189600,XLF
17,4/25/2016,Good Friday,43.320000,43.470001,43.209999,43.450001,41.344475,9357500,XLK
18,4/25/2016,Good Friday,31.504999,31.681000,31.504999,31.681000,28.249432,2300,XLRE
19,4/25/2016,Good Friday,47.150002,47.450001,47.119999,47.439999,42.575371,12742900,XLU
20,4/25/2016,Good Friday,71.599998,71.820000,71.360001,71.589996,68.023193,8937500,XLV
21,4/25/2016,Good Friday,79.309998,79.559998,78.989998,79.550003,76.010315,3897200,XLY
22,4/30/2018,Good Friday,57.849998,58.049999,56.950001,57.009998,55.538433,4875200,XLB
23,4/30/2018,Good Friday,73.699997,74.639999,73.680000,73.809998,70.930481,12963200,XLE
24,4/30/2018,Good Friday,27.770000,27.920000,27.440001,27.450001,26.768534,41731400,XLF
25,4/30/2018,Good Friday,66.059998,66.470001,65.379997,65.459999,64.291977,8686100,XLK
26,4/30/2018,Good Friday,30.940001,31.129999,30.850000,30.889999,29.552002,2895500,XLRE
27,4/30/2018,Good Friday,51.790001,51.959999,51.509998,51.560001,49.456478,12746000,XLU
28,4/30/2018,Good Friday,83.900002,83.949997,82.250000,82.260002,80.623726,7241000,XLV
29,4/30/2018,Good Friday,104.589996,105.129997,103.690002,103.699997,102.016479,5003100,XLY
30,4/21/2008,Good Friday,44.099998,44.509998,43.840000,44.349998,34.370510,9763300,XLB
31,4/21/2008,Good Friday,83.760002,84.660004,83.339996,84.540001,65.499763,15824300,XLE
32,4/21/2008,Good Friday,21.275387,21.283510,20.966694,21.169781,12.922755,80684200,XLF
33,4/21/2008,Good Friday,23.760000,24.010000,23.700001,23.969999,19.923275,5295100,XLK
34,4/21/2008,Good Friday,40.450001,40.689999,40.049999,40.310001,26.431408,3507100,XLU
35,4/21/2008,Good Friday,31.520000,31.650000,31.459999,31.530001,25.905060,3293800,XLV
36,4/21/2008,Good Friday,31.920000,32.080002,31.730000,32.070000,27.035278,3426100,XLY
37,4/25/2005,Good Friday,28.100000,28.430000,28.100000,28.360001,20.503197,956200,XLB
38,4/25/2005,Good Friday,42.400002,42.889999,42.310001,42.630001,31.864290,12958500,XLE
39,4/25/2005,Good Friday,22.737612,22.843218,22.623882,22.818846,12.898719,3569000,XLF
40,4/25/2005,Good Friday,18.920000,19.049999,18.879999,18.950001,15.405841,772100,XLK
41,4/25/2005,Good Friday,29.900000,29.969999,29.750000,29.920000,17.903051,647300,XLU
42,4/25/2005,Good Friday,30.600000,30.700001,30.430000,30.559999,24.030184,344500,XLV
43,4/25/2005,Good Friday,31.559999,31.660000,31.410000,31.620001,25.864315,502900,XLY
44,4/29/2002,Good Friday,22.500000,22.520000,22.170000,22.230000,15.107199,745600,XLB
45,4/29/2002,Good Friday,27.799999,27.889999,27.540001,27.620001,19.535580,102300,XLE
46,4/29/2002,Good Friday,21.413485,21.543461,21.202274,21.242891,11.278547,1378400,XLF
47,4/29/2002,Good Friday,18.760000,19.059999,18.549999,18.680000,14.746543,960800,XLK
48,4/29/2002,Good Friday,26.400000,26.400000,25.920000,25.920000,13.849947,226900,XLU
49,4/29/2002,Good Friday,29.620001,29.700001,29.000000,29.120001,22.136473,702900,XLV

In [13]:
merge_table2=pd.merge(merge_table, friday, how="outer", on="Date")
merge_table2.head(100)

,Date,Holiday,Open,High,Low,Close,Adj Close,Volume,Ticker
0,12/31/2010,New Year's Day,38.389999,38.540001,38.310001,38.410000,32.195354,2424700.0,XLB
1,12/31/2010,New Year's Day,68.129997,68.500000,67.930000,68.250000,55.488960,4444500.0,XLE
2,12/31/2010,New Year's Day,12.908205,12.973192,12.891957,12.956945,8.443467,27080300.0,XLF
3,12/31/2010,New Year's Day,25.209999,25.240000,25.090000,25.190001,21.842997,6352100.0,XLK
4,12/31/2010,New Year's Day,31.330000,31.459999,31.290001,31.340000,23.045191,2171300.0,XLU
5,12/31/2010,New Year's Day,31.540001,31.570000,31.430000,31.500000,27.345753,3908500.0,XLV
6,12/31/2010,New Year's Day,37.470001,37.480000,37.290001,37.410000,33.062931,2212600.0,XLY
7,4/29/2013,Good Friday,39.009998,39.529999,38.880001,39.490002,34.744102,6944200.0,XLB
8,4/29/2013,Good Friday,77.650002,78.279999,77.300003,77.959999,65.830391,12214700.0,XLE
9,4/29/2013,Good Friday,15.150285,15.174655,15.085297,15.150285,10.257263,36910900.0,XLF
10,4/29/2013,Good Friday,30.110001,30.549999,30.110001,30.469999,27.405146,8256000.0,XLK
11,4/29/2013,Good Friday,41.130001,41.380001,40.930000,41.320000,33.249065,5835800.0,XLU
12,4/29/2013,Good Friday,47.580002,47.860001,47.580002,47.689999,43.326698,3950000.0,XLV
13,4/29/2013,Good Friday,54.509998,54.669998,54.279999,54.459999,49.873486,3157800.0,XLY
14,4/25/2016,Good Friday,47.160000,47.160000,46.689999,47.049999,44.099194,4601900.0,XLB
15,4/25/2016,Good Friday,66.809998,66.820000,65.790001,66.290001,60.142891,17234300.0,XLE
16,4/25/2016,Good Friday,19.049553,19.106417,18.952072,19.090170,13.803587,38189600.0,XLF
17,4/25/2016,Good Friday,43.320000,43.470001,43.209999,43.450001,41.344475,9357500.0,XLK
18,4/25/2016,Good Friday,31.504999,31.681000,31.504999,31.681000,28.249432,2300.0,XLRE
19,4/25/2016,Good Friday,47.150002,47.450001,47.119999,47.439999,42.575371,12742900.0,XLU
20,4/25/2016,Good Friday,71.599998,71.820000,71.360001,71.589996,68.023193,8937500.0,XLV
21,4/25/2016,Good Friday,79.309998,79.559998,78.989998,79.550003,76.010315,3897200.0,XLY
22,4/30/2018,Good Friday,57.849998,58.049999,56.950001,57.009998,55.538433,4875200.0,XLB
23,4/30/2018,Good Friday,73.699997,74.639999,73.680000,73.809998,70.930481,12963200.0,XLE
24,4/30/2018,Good Friday,27.770000,27.920000,27.440001,27.450001,26.768534,41731400.0,XLF
25,4/30/2018,Good Friday,66.059998,66.470001,65.379997,65.459999,64.291977,8686100.0,XLK
26,4/30/2018,Good Friday,30.940001,31.129999,30.850000,30.889999,29.552002,2895500.0,XLRE
27,4/30/2018,Good Friday,51.790001,51.959999,51.509998,51.560001,49.456478,12746000.0,XLU
28,4/30/2018,Good Friday,83.900002,83.949997,82.250000,82.260002,80.623726,7241000.0,XLV
29,4/30/2018,Good Friday,104.589996,105.129997,103.690002,103.699997,102.016479,5003100.0,XLY
...,...,...,...,...,...,...,...,...,...
70,11/14/2001,(World Trade Center Day),26.100000,26.100000,25.700001,25.750000,19.531305,11400.0,XLV
71,11/14/2001,(World Trade Center Day),27.150000,27.160000,26.840000,27.150000,21.687817,116400.0,XLY
72,2001-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,2001-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,2001-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,2001-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,2001-02-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,2001-02-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2001-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2001-02-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2001-03-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,2001-03-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,2001-03-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2001-03-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,2001-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,2001-04-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,2001-04-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,2001-04-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2001-04-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,2001-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,2001-05-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,2001-05-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2001-05-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,2001-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,2001-06-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,2001-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,2001-06-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,2001-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2001-07-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,2001-07-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
merge_table2.columns

Index(['Date', 'Holiday', 'Open', 'High', 'Low', 'Close', 'Adj Close',
       'Volume', 'Ticker'],
      dtype='object')

In [15]:
merge_table2["Days of Week"]=dt.datetime.weekday

In [16]:
merge_table2.head()

,Date,Holiday,Open,High,Low,Close,Adj Close,Volume,Ticker,Days of Week
0,12/31/2010,New Year's Day,38.389999,38.540001,38.310001,38.410000,32.195354,2424700.0,XLB,<method 'weekday' of 'datetime.date' objects>
1,12/31/2010,New Year's Day,68.129997,68.500000,67.930000,68.250000,55.488960,4444500.0,XLE,<method 'weekday' of 'datetime.date' objects>
2,12/31/2010,New Year's Day,12.908205,12.973192,12.891957,12.956945,8.443467,27080300.0,XLF,<method 'weekday' of 'datetime.date' objects>
3,12/31/2010,New Year's Day,25.209999,25.240000,25.090000,25.190001,21.842997,6352100.0,XLK,<method 'weekday' of 'datetime.date' objects>
4,12/31/2010,New Year's Day,31.330000,31.459999,31.290001,31.340000,23.045191,2171300.0,XLU,<method 'weekday' of 'datetime.date' objects>

In [17]:
merge_table2["Days of Week"]=pd.to_datetime(merge_table2.Date).dt.day_name()

In [18]:
merge_table2.head(50)

,Date,Holiday,Open,High,Low,Close,Adj Close,Volume,Ticker,Days of Week
0,12/31/2010,New Year's Day,38.389999,38.540001,38.310001,38.410000,32.195354,2424700.0,XLB,Friday
1,12/31/2010,New Year's Day,68.129997,68.500000,67.930000,68.250000,55.488960,4444500.0,XLE,Friday
2,12/31/2010,New Year's Day,12.908205,12.973192,12.891957,12.956945,8.443467,27080300.0,XLF,Friday
3,12/31/2010,New Year's Day,25.209999,25.240000,25.090000,25.190001,21.842997,6352100.0,XLK,Friday
4,12/31/2010,New Year's Day,31.330000,31.459999,31.290001,31.340000,23.045191,2171300.0,XLU,Friday
5,12/31/2010,New Year's Day,31.540001,31.570000,31.430000,31.500000,27.345753,3908500.0,XLV,Friday
6,12/31/2010,New Year's Day,37.470001,37.480000,37.290001,37.410000,33.062931,2212600.0,XLY,Friday
7,4/29/2013,Good Friday,39.009998,39.529999,38.880001,39.490002,34.744102,6944200.0,XLB,Monday
8,4/29/2013,Good Friday,77.650002,78.279999,77.300003,77.959999,65.830391,12214700.0,XLE,Monday
9,4/29/2013,Good Friday,15.150285,15.174655,15.085297,15.150285,10.257263,36910900.0,XLF,Monday
10,4/29/2013,Good Friday,30.110001,30.549999,30.110001,30.469999,27.405146,8256000.0,XLK,Monday
11,4/29/2013,Good Friday,41.130001,41.380001,40.930000,41.320000,33.249065,5835800.0,XLU,Monday
12,4/29/2013,Good Friday,47.580002,47.860001,47.580002,47.689999,43.326698,3950000.0,XLV,Monday
13,4/29/2013,Good Friday,54.509998,54.669998,54.279999,54.459999,49.873486,3157800.0,XLY,Monday
14,4/25/2016,Good Friday,47.160000,47.160000,46.689999,47.049999,44.099194,4601900.0,XLB,Monday
15,4/25/2016,Good Friday,66.809998,66.820000,65.790001,66.290001,60.142891,17234300.0,XLE,Monday
16,4/25/2016,Good Friday,19.049553,19.106417,18.952072,19.090170,13.803587,38189600.0,XLF,Monday
17,4/25/2016,Good Friday,43.320000,43.470001,43.209999,43.450001,41.344475,9357500.0,XLK,Monday
18,4/25/2016,Good Friday,31.504999,31.681000,31.504999,31.681000,28.249432,2300.0,XLRE,Monday
19,4/25/2016,Good Friday,47.150002,47.450001,47.119999,47.439999,42.575371,12742900.0,XLU,Monday
20,4/25/2016,Good Friday,71.599998,71.820000,71.360001,71.589996,68.023193,8937500.0,XLV,Monday
21,4/25/2016,Good Friday,79.309998,79.559998,78.989998,79.550003,76.010315,3897200.0,XLY,Monday
22,4/30/2018,Good Friday,57.849998,58.049999,56.950001,57.009998,55.538433,4875200.0,XLB,Monday
23,4/30/2018,Good Friday,73.699997,74.639999,73.680000,73.809998,70.930481,12963200.0,XLE,Monday
24,4/30/2018,Good Friday,27.770000,27.920000,27.440001,27.450001,26.768534,41731400.0,XLF,Monday
25,4/30/2018,Good Friday,66.059998,66.470001,65.379997,65.459999,64.291977,8686100.0,XLK,Monday
26,4/30/2018,Good Friday,30.940001,31.129999,30.850000,30.889999,29.552002,2895500.0,XLRE,Monday
27,4/30/2018,Good Friday,51.790001,51.959999,51.509998,51.560001,49.456478,12746000.0,XLU,Monday
28,4/30/2018,Good Friday,83.900002,83.949997,82.250000,82.260002,80.623726,7241000.0,XLV,Monday
29,4/30/2018,Good Friday,104.589996,105.129997,103.690002,103.699997,102.016479,5003100.0,XLY,Monday
30,4/21/2008,Good Friday,44.099998,44.509998,43.840000,44.349998,34.370510,9763300.0,XLB,Monday
31,4/21/2008,Good Friday,83.760002,84.660004,83.339996,84.540001,65.499763,15824300.0,XLE,Monday
32,4/21/2008,Good Friday,21.275387,21.283510,20.966694,21.169781,12.922755,80684200.0,XLF,Monday
33,4/21/2008,Good Friday,23.760000,24.010000,23.700001,23.969999,19.923275,5295100.0,XLK,Monday
34,4/21/2008,Good Friday,40.450001,40.689999,40.049999,40.310001,26.431408,3507100.0,XLU,Monday
35,4/21/2008,Good Friday,31.520000,31.650000,31.459999,31.530001,25.905060,3293800.0,XLV,Monday
36,4/21/2008,Good Friday,31.920000,32.080002,31.730000,32.070000,27.035278,3426100.0,XLY,Monday
37,4/25/2005,Good Friday,28.100000,28.430000,28.100000,28.360001,20.503197,956200.0,XLB,Monday
38,4/25/2005,Good Friday,42.400002,42.889999,42.310001,42.630001,31.864290,12958500.0,XLE,Monday
39,4/25/2005,Good Friday,22.737612,22.843218,22.623882,22.818846,12.898719,3569000.0,XLF,Monday
40,4/25/2005,Good Friday,18.920000,19.049999,18.879999,18.950001,15.405841,772100.0,XLK,Monday
41,4/25/2005,Good Friday,29.900000,29.969999,29.750000,29.920000,17.903051,647300.0,XLU,Monday
42,4/25/2005,Good Friday,30.600000,30.700001,30.430000,30.559999,24.030184,344500.0,XLV,Monday
43,4/25/2005,Good Friday,31.559999,31.660000,31.410000,31.620001,25.864315,502900.0,XLY,Monday
44,4/29/2002,Good Friday,22.500000,22.520000,22.170000,22.230000,15.107199,745600.0,XLB,Monday
45,4/29/2002,Good Friday,27.799999,27.889999,27.540001,27.620001,19.535580,102300.0,XLE,Monday
46,4/29/2002,Good Friday,21.413485,21.543461,21.202274,21.242891,11.278547,1378400.0,XLF,Monday
47,4/29/2002,Good Friday,18.760000,19.059999,18.549999,18.680000,14.746543,960800.0,XLK,Monday
48,4/29/2002,Good Friday,26.400000,26.400000,25.920000,25.920000,13.849947,226900.0,XLU,Monday
49,4/29/2002,Good Friday,29.620001,29.700001,29.000000,29.120001,22.136473,702900.0,XLV,Monday

In [19]:
x_axis = np.arange(0, len(merge_table2), 0.1)